proxy_url = ''

urls = [
  # https://www.pornhub.com/categories

  # "https://www.pornhub.com/video?o=tr",
  # "https://www.pornhub.com/video?o=ht",
  "https://www.pornhub.com/video?o=mv",
  "https://cn.pornhub.com/view_video.php?viewkey=ph61d44ed3c7ada",
]
